# Generated by Django 3.2.7 on 2021-11-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('idasesoria', models.IntegerField(primary_key=True, serialize=False)),
                ('fechaasesoria', models.DateField()),
                ('cantaccidentes', models.IntegerField()),
                ('tasaaccidentes', models.FloatField()),
                ('valorasesoria', models.IntegerField()),
            ],
            options={
                'db_table': 'asesoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Capacitaciones',
            fields=[
                ('idcapacitacion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fechacapacitacion', models.CharField(max_length=100)),
                ('horacapacitacion', models.CharField(max_length=100)),
                ('cantasistentes', models.BigIntegerField()),
                ('estado', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'capacitaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idcomuna', models.IntegerField(primary_key=True, serialize=False)),
                ('nombrecomuna', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('idcontrato', models.BooleanField(primary_key=True, serialize=False)),
                ('desccontrato', models.CharField(max_length=10)),
                ('fechainiciocontrato', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('rutemp', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombreemp', models.CharField(max_length=15)),
                ('direccionemp', models.CharField(max_length=100)),
                ('telefonoemp', models.BigIntegerField()),
                ('correoemp', models.CharField(max_length=100)),
                ('rubroempresa', models.CharField(blank=True, max_length=100, null=True)),
                ('digitoveriemp', models.FloatField()),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idsexo', models.IntegerField(primary_key=True, serialize=False)),
                ('descsexo', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'genero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('idjornada', models.IntegerField(primary_key=True, serialize=False)),
                ('descjornada', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'jornada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pagoplan',
            fields=[
                ('idpago', models.IntegerField(primary_key=True, serialize=False)),
                ('fechapago', models.CharField(max_length=100)),
                ('estadopago', models.CharField(max_length=100)),
                ('montopago', models.IntegerField()),
            ],
            options={
                'db_table': 'pagoplan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('idperfil', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'perfil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('idplan', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreplan', models.CharField(max_length=25)),
                ('cantvisitas', models.IntegerField()),
                ('cantasesorias', models.IntegerField()),
                ('cantcapacitacion', models.IntegerField()),
                ('valorplan', models.IntegerField()),
            ],
            options={
                'db_table': 'plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('idprofesion', models.IntegerField(primary_key=True, serialize=False)),
                ('pr_descripcion', models.CharField(max_length=12)),
                ('pr_sueldo', models.IntegerField()),
                ('pr_especialidad', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'profesion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('runprf', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pnombreprf', models.CharField(max_length=15)),
                ('apellidopatprf', models.CharField(max_length=20)),
                ('apellidomatprf', models.CharField(max_length=20)),
                ('edadprf', models.IntegerField()),
                ('correoprf', models.CharField(max_length=100)),
                ('telefonoprf', models.CharField(max_length=13)),
                ('fechanacprf', models.CharField(max_length=100)),
                ('direccionprf', models.CharField(max_length=50)),
                ('experienciaprf', models.IntegerField()),
                ('fechacontrataprf', models.CharField(max_length=100)),
                ('paisnacimientoprf', models.CharField(max_length=10)),
                ('digitoverificadorprf', models.FloatField()),
                ('contrasenaprf', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'profesional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idregion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreregion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('idregistro', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('item1', models.CharField(max_length=1)),
                ('item2', models.CharField(max_length=1)),
                ('item3', models.CharField(max_length=1)),
                ('comentarioitem1', models.CharField(max_length=100)),
                ('comentarioitem2', models.CharField(max_length=100)),
                ('comentarioitem3', models.CharField(max_length=100)),
                ('itemextra1', models.CharField(blank=True, max_length=1, null=True)),
                ('itemextra2', models.CharField(blank=True, max_length=1, null=True)),
                ('itemextra3', models.CharField(blank=True, max_length=1, null=True)),
                ('comentarioitemextra1', models.CharField(blank=True, max_length=100, null=True)),
                ('comentarioitemextra2', models.CharField(blank=True, max_length=100, null=True)),
                ('comentarioitemextra3', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'registro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('rutrepresent', models.FloatField(primary_key=True, serialize=False)),
                ('digitoverirepresent', models.FloatField()),
                ('nombrerepre', models.CharField(max_length=12)),
                ('apellidorepre', models.CharField(max_length=12)),
                ('cargorepre', models.CharField(max_length=12)),
                ('numeroreprese', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'representante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipocontrato',
            fields=[
                ('idtipocontrato', models.IntegerField(primary_key=True, serialize=False)),
                ('desctipocontrato', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'tipocontrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visitas',
            fields=[
                ('idvisita', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fechavisita', models.CharField(max_length=100)),
                ('tipovisitas', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'visitas',
                'managed': False,
            },
        ),
    ]
